language: node_js
node_js:
  # latest node version
  - "node"
  # latest stable release
  # - "lts/*"
  # Specific version
  # - "8"

cache:
  npm: true
  directories:
    - node_modules
# install:
#   - npm install

# stages:
#   # - test
#   - build
#   - deploy
#   - killcache

# build_prod:
#   stage: build


before_script:
  - npm install -g pug-cli
  #c- npm install -g parcel pug-cli --unsafe-perm=true

script:
  - mkdir dist
  - npm run build
  - ls dist
  # - mkdir dist
  # - npm run build-stylus
  # - npm run build-pug
  # - ls dist
  # - npm test
  

before_deploy:
  - npm install -g travis-ci-cloudfront-invalidation

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $BUCKET_NAME
  skip_cleanup: true
  local-dir: dist
  on:
    branch: master

after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $CLOUDFRONT_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
